### ISSUE TITLE
cpu and gpu usage when not being used is very high

### ISSUE THREAD

**Issue by gedw99** [oligo/gioview#1]
cpu and gpu usage when not being used is very high when running the example on an a Mac m2

CPU is around 50 % even when minimised
GPU is about 17 %

What  about on your machine ?

**Comment by oligo** [comment]
Attach CPU profiling data for Gio v0.5.0(before_cpu.pprof) and v0.6.0(after_cpu.pprof)
[cpu_profiling.zip](https://github.com/oligo/gioview/files/15224670/cpu_profiling.zip)

**Comment by gedw99** [comment]
Def worth raising an issue with the gio team on source but ?

you have a reproducible bug imho

**Comment by gedw99** [comment]
Btw the tree view is awesome .

**Comment by gedw99** [comment]
https://github.com/gioui/gio-example on v0.6 also has same issues from my brief testing.

**Comment by gedw99** [comment]
its a regression

https://github.com/gioui/gio-example running tabs example

<img width="1728" alt="Screenshot 2024-05-07 at 10 56 29" src="https://github.com/oligo/gioview/assets/53147028/4b07fdeb-2bc2-406a-90d9-3d14a070a835">

**Comment by gedw99** [comment]
I tried a few examples in https://github.com/gioui/gio-example that is based on v0.6 and I am NOT seeing the high CPU GPU issues.

**Comment by oligo** [comment]
Hi I fixed this issue. It turns out to be the problem of setting window title in View Manager. Setting window options in Gio v0.6.0 seems to be a costly operation.
