### ISSUE TITLE
Paint Selection when editor is focused

### ISSUE THREAD

**Issue by mirzakhany** [oligo/gioview#13]
Hi,
As result of flowing change in editor widget, user can have more one selected text if have more than one editor in the same view. its not a logical issue but can cause UX problems. I did test to revert this change and editor still works with no issue so I was wondering if we can remove it?

```
	// comment below code to ensure selected text is highlighted when editor menu poped up.
	// if !gtx.Focused(e) {
	// 	return
	// }
```

Screen Shot:

<img width="336" alt="Screenshot 2024-08-03 at 19 46 59" src="https://github.com/user-attachments/assets/6894f086-f84e-4443-a4c5-0fec2cf6fc72">

**Comment by oligo** [comment]
I used context menu in editor where selected text have to be highlighted even when the menu get focused. This is another scenario that I want to support. So may be there needs another config option to enable this feature.  What do you think?

On the other hand, I am thinking about building a dedicated project focusing on a non- general editor that has more features, targeting long text, or source code editing, even for rich text. This could keep editor in Gioview simple,  and only the required features have to be added(or contribute the required features to Gio?).

**Comment by mirzakhany** [comment]
Thanks sounds good to me.
I also think it would nice to have a separate project for a non-general editor. specially for syntax highlighting, things like autocomplete and support for long text. I'll be happy to help with that.
