### ISSUE TITLE
Question on editor and scrollbar 

### ISSUE THREAD

**Issue by mirzakhany** [oligo/gioview#17]
Hi, First of all, thanks for your great work on this project 🙏 

I have a question regarding the editor widget. I was wondering if you have any example of adding scrollbars to it? I see that editor is exposing `ViewPortRatio` and `ScrollByRatio`. how would you recommend using them to add scrollbar to the editor.

Thanks

**Comment by oligo** [comment]
Sure.  Method `ViewPortRatio` is used to get the viewport offset in ratio. That is required to feed into `material.Scrollbar`.
On the other hand, `ScollByRatio` is setting the scroll distance. Here is a snippet to show you the way it works:

```go
scrollbarStyle := material.Scrollbar(th.Theme, &me.scrollbar)
editorDims = func(gtx C) D {
	return layout.Inset{
		Left:   unit.Dp(20),
		Right:  unit.Dp(20),
		Top:    unit.Dp(10),
		Bottom: unit.Dp(10),
	}.Layout(gtx, func(gtx C) D {
		return editor.NewEditor(me.state, me.editorConf, "").Layout(gtx)
	})

}(gtx)

//calculate start, end from  me.editor.
layout.E.Layout(gtx, func(gtx layout.Context) layout.Dimensions {
	viewportStart, viewportEnd := me.state.ViewPortRatio()
	return scrollbarStyle.Layout(gtx, layout.Vertical, viewportStart, viewportEnd)
})

if delta := me.scrollbar.ScrollDistance(); delta != 0 {
	// Handle any changes to the text position as a result of user interaction
	// with the scrollbar.
	me.state.ScrollByRatio(gtx, delta)
}

return editorDims
```

In the code above, `me.scollbar` is a `widget.Scrollbar`, and state is a `gioview Editor`. 

Hope this helps.

**Comment by mirzakhany** [comment]
Its working perfectly thanks a lot.
