### ISSUE TITLE
v0.7 tagged to make development smoother

### ISSUE THREAD

**Issue by gedw99** [oligo/gioview#6]
There is now the first tagged version of the gio cmd here:

https://github.com/gioui/gio-cmd/releases/tag/v0.7.0

It matches the other gio repos too:

https://github.com/gioui/gio/releases/tag/v0.7.0

https://github.com/gioui/gio-x/releases/tag/v0.7.0

**Comment by oligo** [comment]
Hi, gio and gio-x are all upgraded to v0.7.

**Comment by ddkwork** [comment]
0.8 is released

**Comment by oligo** [comment]
> 0.8 is released

@ddkwork Thanks! A new version is released which aligns with the latest v0.8.0 of Gio.

**Comment by ddkwork** [comment]
> > 0.8 is released
> 
> @ddkwork Thanks! A new version is released which aligns with the latest v0.8.0 of Gio.

多谢，因为我也在引用您的代码编辑器控件
https://github.com/ddkwork/ux

此外，如果您有空方便协助我优化一下这个树形表格吗？目前就qt和web有这种控件，安卓上的长按弹出右键菜单似乎不被gio支持。

**Comment by oligo** [comment]
> > > 0.8 is released
> > 
> > 
> > [@ddkwork](https://github.com/ddkwork) Thanks! A new version is released which aligns with the latest v0.8.0 of Gio.
> 
> 多谢，因为我也在引用您的代码编辑器控件 https://github.com/ddkwork/ux
> 
> 此外，如果您有空方便协助我优化一下这个树形表格吗？目前就qt和web有这种控件，安卓上的长按弹出右键菜单似乎不被gio支持。

你可以加一个issue, 看看我能怎么帮你

**Comment by ddkwork** [comment]
> > > > 0.8 is released
> > > 
> > > 
> > > [@ddkwork](https://github.com/ddkwork) Thanks! A new version is released which aligns with the latest v0.8.0 of Gio.
> > 
> > 多谢，因为我也在引用您的代码编辑器控件 https://github.com/ddkwork/ux
> > 
> > 此外，如果您有空方便协助我优化一下这个树形表格吗？目前就qt和web有这种控件，安卓上的长按弹出右键菜单似乎不被gio支持。
> 
> 你可以加一个issue, 看看我能怎么帮你


很多问题，要完善qt6的treewidget那些特性太麻烦了，拖放json文件加载所有节点到树形表格目前我是go mod vendor一下本地修改，gio似乎不支持拖放文件。下面的就是目前这个treegrid的实现困扰，谢谢你，大师傅。

https://github.com/ddkwork/ux/issues/4

https://github.com/ddkwork/ux/issues/6

https://github.com/ddkwork/ux/issues/9

https://github.com/ddkwork/ux/issues/10

https://github.com/ddkwork/ux/issues/3

https://github.com/ddkwork/ux/issues/2
