### ISSUE TITLE
Syntax Highlighting in Editor

### ISSUE THREAD

**Issue by mirzakhany** [oligo/gioview#7]
Hi @oligo 
First of all thanks for your great work on this package, its looks really good. 
I have developed an API Client with gio ui, [Chapar](https://github.com/chapar-rest/chapar) and from very beginning one of my concerns was syntax highlighting for JSON and soon for python codes. 

That being said I would like to have your review on the [PR I made in Chapar](https://github.com/chapar-rest/chapar/pull/53) which is using gioview editor to enable syntax highlighting. your feedback is very much appreciated. 

Thanks again
Mohsen

**Comment by oligo** [comment]
Hi @mirzakhany 
Glad to see you are using gioview in Chapar. Please see my comments in [#53](https://github.com/chapar-rest/chapar/pull/53#pullrequestreview-2186056337). Hope it helps.

**Comment by mirzakhany** [comment]
Thanks for you comments 💯
